### ISSUE TITLE
Symbol's function definition is void: defstruct

### ISSUE THREAD

**Issue by fraya** [deech/shen-elisp#2]
After install from quelpa, `M-x shen/repl`, 
shows this error: 

`Symbol's function definition is void: defstruct`

My system is:
- Ubuntu Linux 16.04 
- Linux 4.4.0-21-generic #37-Ubuntu SMP x86_64 GNU/Linux
- GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9 of 2016-04-17 on lgw01-04, modified by Debian

**Comment by deech** [comment]
Should be fixed now. Could you try again? Thanks!

**Comment by fraya** [comment]
Works! 
Thank you very much!
