### ISSUE TITLE
Show to how load lib manually

### ISSUE THREAD

**Issue by joelmccracken** [deech/shen-elisp#22]
I don't use either spacemacs or quelpa, so I had to do some finaggling to get this to to work. I'll show the code I used this evening when I get to that computer, but I was able to load it without that much problem.

I can also just document it on my branch, in case you don't want to keep working on this project.

**Comment by deech** [comment]
That sounds like a great addition to `README.org`! I'll happily merge that PR.

**Comment by joelmccracken** [comment]
you know, on second though, my script, while it works, is really... janky. but for now, anyone who wants to run this, I had this work:

```
(add-to-list 'load-path (file-name-directory (buffer-file-name)))

(defun runner ()
  (interactive)
  (progn
    (load "install.el")
    (compile-and-load "shen-primitives.el")
    ;; (compile-and-load "install.el")
    (eval-klambda-files *klambda-files*)
    (compile-and-load "shen-elisp.el")
    (compile-and-load "shen-overlays.el")
    (compile-and-load "shen-repl.el")
    (shen/repl)))
```
I'd like to see if I can separate the compile step from the load step so that loading/initializing the shen environment doesn't freeze emacs for several seconds.

**Comment by joelmccracken** [comment]
After cleaning things up a bit in my branch (this commit: https://github.com/joelmccracken/shen-elisp/commit/e4e16d3b03f64fca91cdcc521a9bf4c8fe7b8376), i can now load it vija:

```
(add-to-list 'load-path "~/Projects/shen-elisp/")
(load "install")
(load-shen)
```

Probably next step will be to clean things up a bit further. I'd love to have this be something that is just super easy to run, and then someone can just `(require 'shen-elisp)` and then `(shen/load "my-script.shen")` and have it work.

**Comment by joelmccracken** [comment]
Upon reflection, I think I understand something; that install.el file is really a lot of utility code that you used during development, but its not really part of the "final product", is it? If that's the case, then things make a lot more sense. 

Thanks a ton for doing all of this work!

**Comment by deech** [comment]
You're welcome. 

Yes, `install.el` is just a [bootstrapping process](https://github.com/deech/shen-elisp/blob/master/shen-elisp.org#bootstrap) and should probably be called `bootstrap.el`. I haven't touched Shen for years and I just tried to load up a repl and, wow, it's pretty rough. Sorry about that.

Also just FYI this implementation is years behind [the current version of the Shen kernel](https://shenlanguage.org/download.html) and having stepped away from Shen I don't currently plan to devote any time to bringing it up to date.

**Comment by joelmccracken** [comment]
Anyway, i'll probably get a PR together soon. How do you feel about putting this in e.g. melpa

**Comment by deech** [comment]
That's possible. I didn't put it up earlier because I still considered it not ready for real use, if you think it is I'll reconsider.

Also if you are planning extensive changes would you be willing to stick with literate style and keep documentation up to date, editing the `shen-elisp.org` instead of adding to the `.el` files directly?

**Comment by joelmccracken** [comment]
totally. I actually prefer literate style, I just tend to go in phases
where when i have no idea what  i'm doing and I edit the built files, then
go back and backport fixes once I know what's up to the org files.

Its not a great habit, but its one I def have. I do it a lot in my personal
workstation project.

**Comment by joelmccracken** [comment]
How much are you interested in discussing/collaborating on future direction/changes to this lib? I"m not sure if shen still holds your interest in any way any longer.

**Comment by deech** [comment]
I'll help out but as you say I'm not interested in Shen for the time being. I've added you as collaborator so you are free to make any changes you want.

**Comment by joelmccracken** [comment]
I guess the main thing I'd appreciate is some code review; I'm just not sure why some things are the way they are, if they just happened to be that way, or if there are any chesterton's fences I need to watch for. For example, tweaked a few things in the actual code for this README change, shen/repl doesn't work if I just download/install the project with the code i showed above, it needs to be byte compiled first, because of how the shen/repl function loads dependencies, explicilty loads foo.elc. You'll see with the PR.

Specific, actual question for you: did you do anything special with your emacs tangling setup? I just ran org-babel-tangle  and every single line is indented two spaces to the right than when it was last tangled.

**Comment by joelmccracken** [comment]
Nevermind, I figured out the problem. Sorry
