### ISSUE TITLE
Provide elpa package

### ISSUE THREAD

**Issue by markokocic** [deech/shen-elisp#4]
It would be great if shen-lisp could be installed using melpa and melpa-stable repositories.

It's nice that it supports spacemacs, but melpa is still "the" standard package manager.

**Comment by deech** [comment]
It is currently available via Melpa. I'll update the README and close the issue.

**Comment by markokocic** [comment]
Indeed, it is available on melpa.org, but still not on stable.melpa.org, which can be an issue for people that use it instead of default melpa.

**Comment by deech** [comment]
Ah, good point! Since this is new software I don't feel comfortable calling it stable because of frequent updates. Do you still think it's a candidate for melpa-stable?

**Comment by markokocic** [comment]
I would say so, but it's your call. My understanding is that melpa stable is used for "releases", so whenever one makes a release, it should be on stable. Version number, e.g 0.1 would be enough of a hinweis about the status. Regular, non-stable melpa is more for "latest and greatest" software. At least that's how some other software uses them.

**Comment by markokocic** [comment]
Just looking into the date of the last message, it's more than one year old now. Is there a chance on getting it into melpa stable?

**Comment by deech** [comment]
I just cut the `0.1` release. Do you know of `stable.melpa.org` will automatically pick it up?

**Comment by markokocic** [comment]
I see it in the elpa stable package index on their web site, but for some reason it doesn't appear in the package list in my emacs.

**Comment by markokocic** [comment]
I can confirm that it now works, so closing this issue.
Thanks a lot.
However, I will be opening few more enhancements requests / questions / bugs.
