### ISSUE TITLE
Typechecker fails with "fwhen expects a boolean"

### ISSUE THREAD

**Issue by poldy** [deech/shen-elisp#6]
I tried to debug this, but got stuck.

Download http://rosettacode.org/wiki/Conway%27s_Game_of_Life#Shen to a file, say "life2.shen".

M-x shen/repl
(load "life2.shen")
;; everything works
^X-k
M-x shen/repl
(tc +)
(load "life2.shen")
;; outputs "(shen/error fwhen expects a boolean: not []%)"
;; looks like it fails when trying to type-check "neighbors"

The weird thing is, the first line of life2.shen is "(tc +)".

This is with v20160522.1457 from melpa, which I think is the latest.

**Comment by poldy** [comment]
When checking this with Shen/SBCL (everything worked), I just noticed something. "(tc +)" seems to only have an effect at the top-level, not in a file like that. So the first, passing, test case above didn't do type-checking.

**Comment by deech** [comment]
I just fixed it. Thanks for the report! Also, yes `(tc +)` must be at the toplevel. It can also be in a `(do ...)` form, for instance, `(do (tc +) (load "life2.shen"))` should also work. But at the top of a file it has no effect.

**Comment by poldy** [comment]
Wow, that was quick. Thanks, it works fine now.
